version: "3.9"  # optional since v1.27.0
services:
  caddy:
    image: caddy:latest
    volumes:
      - ./.docker/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
    links:
      - minio
      - phpmyadmin
      - meilisearch

  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_MASTER_KEY=masterKey
    volumes:
      - meilisearch-data:/data.ms

  minio:
    image: quay.io/minio/minio
    environment:
        - MINIO_ROOT_USER=root
        - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  redis:
    image: redis

  db:
    image: bitnami/mariadb:latest
    environment:
        - MARIADB_DATABASE=db
        - MARIADB_ROOT_PASSWORD=password
    volumes:
      - mariadb-data:/bitnami/mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db:mysql

  web:
    image: spiksius/php8.1-apache:latest
    env_file: .env.docker
    volumes:
      - ./:/var/www/
    entrypoint: /var/www/.docker/entrypoint.sh
    links:
      - redis
      - minio
      - db
      - meilisearch

volumes:
    mariadb-data:
    minio-data:
    meilisearch-data:
    web-cache:

# c:/Windows/System32/drivers/etc/hosts file contents needed for testing

# 127.0.0.1 root.internal
# 127.0.0.1 site1.internal
# 127.0.0.1 site2.internal
# 127.0.0.1 site3.internal
# 127.0.0.1 site4.internal
# 127.0.0.1 images.internal
# 127.0.0.1 phpmyadmin.internal
# 127.0.0.1 minio.internal
# 127.0.0.1 meilisearch.internal
#
# 127.0.0.1 www.root.internal
# 127.0.0.1 www.site1.internal
# 127.0.0.1 www.site2.internal
# 127.0.0.1 www.site3.internal
# 127.0.0.1 www.site4.internal
# 127.0.0.1 www.images.internal
# 127.0.0.1 www.phpmyadmin.internal
# 127.0.0.1 www.minio.internal
# 127.0.0.1 www.meilisearch.internal
